### PR TITLE
Password form improvements

### PR DESCRIPTION
**Pull request by fragalcer**
Issues resolved: #927 

Sanity checks:
- [ ] Have tests been run locally?
- [ ] Does this change any javascript? If so, have you checked that the UI works as expected?
- [ ] If there are data model changes, are relevant data standards referenced - in code?
- [ ] If there are deviations from any specified standards, are the reasons for changes documented?
- [ ] If there are UI changes have you documented whats changed so the help documentation can be updated?

### CODE REVIEW

**Comment by LegoStormtroopr** [comment]
This PR has the same changes as #1524 . Is there a missing commit?

**Comment by fragalcer** [comment]
> This PR has the same changes as #1524 . Is there a missing commit?

Yes, there is a missing commit. It is not ready. I will check this tonight.

**Comment by harrywhite4** [comment]
Should be re based to remove issue number commit

**Comment by LegoStormtroopr** [comment]
Can remove/rebase before merge?

**Pull request closed without merging**
