### PR TITLE
Hide matadata items if they are zero

### PR DESCRIPTION
**Pull request by alexbenic**
Adresses #527

### CODE REVIEW

**Comment by LegoStormtroopr** [comment]
Wow, thanks! This is perfect!

Would you mind adding a test to `aristotle_mdr/contrib/browse/tests/test_browse.py` just to verify the correctness of this for future reference?

I know the current coverage stats don't support templates yet, but it will still be neat to have.

Thanks again :)

**Comment by alexbenic** [comment]
Sure, no problem.

**Comment by LegoStormtroopr** [comment]
Any follow upon this?

**Comment by alexbenic** [comment]
I was busy, sorry. I will fix it in the next 10-12 hours.

**Comment by alexbenic** [comment]
Disclaimer: I am very, vary new to Django.

I spent couple of hours trying to get this right, but Django is a bit to magical for me.  I am pretty sure that this is wrong test implementation, and I am not sure how to get it right. 

```self.itemType.objects.count().all()``` will get total number of objects. I don't know how to get individual count. If you can point me to the documentation and/or give me some pointers I can get this right.

 If it is too much trouble just merge it and correct the test and I will check where I made mistakes that way.

**Comment by LegoStormtroopr** [comment]
No need for a disclaimer - I appreciate the help.

From what I can see this looks like a pretty good test. I think from reading the code that the `if` branch of this `if/then/else` will never fire off because the test scaffold you used is making some items for you

        if(self.itemType.objects.all().count() == 0):
            self.assertTrue(self.itemType._meta.model_name not in response.content)
        else:
            self.assertTrue(self.itemType._meta.model_name in response.content)

But, that's because of how much complexity there is in the custom Aristotle stuff. Otherwise the use of `Model.all().count()` is fine.

But if the tests pass I'm happy to merge it in and clean some of that later.

**Comment by alexbenic** [comment]
Yeah, I could do that.

**Pull request merged**
