### PR TITLE
Update django.po

### PR DESCRIPTION
**Pull request by bkaempgen**
I have started to add translations but there are quite a lot of them :-) 

How about we use Google translate via the API automatically to translate all the sentences and I have a look through them for obvious errors.

For example the sentence "You do not have permission to move an item to that workgroup." was perfectly translated by Google [1].

All the best with your open source project!

Best

Benedikt

[1] https://translate.google.de/?oe=utf-8&gws_rd=cr&um=1&ie=UTF-8&hl=de&client=tw-ob#en/de/You%20do%20not%20have%20permission%20to%20move%20an%20item%20to%20that%20workgroup.

### CODE REVIEW

**Comment by LegoStormtroopr** [comment]
This is a great suggestion, and thanks for the work so far.

Due to your suggestion, I've found this library https://github.com/ankitpopli1891/django-autotranslate/

However it needs a translation API key, which is a paid service. I'm happy to set this up and manage the creation of strings if you can review them all. It might take a few days though.

Thanks again!

**Comment by LegoStormtroopr** [comment]
@bkaempgen I was actually able t do this today quite quickly!

The only thing now is to review them and remove the line that indicates its an autotranslation:
```
#, fuzzy
```

Thanks a lot for the idea!

**Comment by LegoStormtroopr** [comment]
@bkaempgen Would you be able to volunteer to check some of the German auto-translation?

**Comment by bkaempgen** [comment]
Hi Samuel,

great that you were able to use Google translate for the descriptions.

I had a quick look at [1].

Small sentences or descriptions look very good. One typo: "SEinige Elemente" should be "Einige Elemente".

However, with longer sentences, the translation has problems:

E.g., "Add an app for app specific help, required for concept help" was translated to "Fügen Sie eine App für App spezifische Hilfe, die für Konzept Hilfe" which does not make much sense. However, the English sentence is not that understandable, either. I would suggest to use simpler english sentences, e.g., by splitting the English sentence to two sentences. Maybe, this will improve the German translation, also. Same goes for sentences such as [2].

I hope that helps.

All the best with your project

Benedikt

[1] https://github.com/aristotle-mdr/aristotle-metadata-registry/blob/develop/aristotle_mdr/locale/de/LC_MESSAGES/django.po 

[2] --------
#: aristotle_mdr/forms/creation_wizards.py:69
#, fuzzy
msgid ""
"The object you are editing has been changed, review the changes before "
"continuing then if you wish to save your changes click the Save button "
"below."
msgstr ""
"Das Objekt, das Sie bearbeiten geändert wurde, um die Änderungen zu "
"überprüfen, bevor Sie fortfahren dann, wenn Sie möchten unter die Änderungen"
" klicken Sie auf die Schaltfläche Speichern zu speichern."

**Pull request merged**
