### PR TITLE
Feature/issue 148

### PR DESCRIPTION
**Pull request by dylan-kerr**
Description has been renamed definition in baseAristotleObject and everywhere that uses it, except for things that look unused or where I couldn't establish inheritance from baseAristotleObject.

Specifically, the following were not changed:

* fixtures/initial_data.yaml.old
* model `GlossaryAdditionalDefinition` in migrations/0001_initial.py
* templates\aristotle_mdr\downloads\pdf\glossaryitem.html
* templates\aristotle_mdr\glossary.html
* templates\aristotle_mdr\static\extensions.html
* templates\aristotle_mdr\user\notice.html
* templates\search\indexes\aristotle_mdr\basepossumobject_text.txt

The CI builds without errors.

### CODE REVIEW

**Comment by LegoStormtroopr** [comment]
Firstly, thanks! What size shirt do you wear? I'll review the changed files over the weekend.

Also, both the glossary files should have been removed when the glossary was spun into its own project.
* `templates\aristotle_mdr\downloads\pdf\glossaryitem.html`
* `templates\aristotle_mdr\glossary.html`

The `fixtures/initial_data.yaml.old` file is just old, old cruft.
Would you mind removing them as part of this pull?

**Comment by LegoStormtroopr** [comment]
Dylan,
This file needs to be reverted: `aristotle_mdr/migrations/0001_initial.py`. Instead just run a new [Django migration](https://docs.djangoproject.com/en/1.8/topics/migrations/) that covers the rename.

Plus while you are doing a migration, could you please you update the below three lines to rename `value_description` as well? Because of the description/definition issue, I had to fudge a different name for them, but this should fix the issue once and for all:

* https://github.com/dylan-kerr/aristotle-metadata-registry/blob/feature/issue-148/aristotle_mdr/models.py#L761
* https://github.com/dylan-kerr/aristotle-metadata-registry/blob/feature/issue-148/aristotle_mdr/models.py#L798
* https://github.com/aristotle-mdr/aristotle-metadata-registry/blob/0ecac0fe6430600bd809286628564af3875c18a2/aristotle_mdr/templates/aristotle_mdr/concepts/valueDomainRepresentation.html#L12
* https://github.com/aristotle-mdr/aristotle-metadata-registry/blob/0ecac0fe6430600bd809286628564af3875c18a2/aristotle_mdr/templates/aristotle_mdr/concepts/valueDomainRepresentation.html#L15

After that, once the travis-ci tests pass I'll merge it in and send you a shirt.

**Comment by dylan-kerr** [comment]
That should cover it.

In regards to the shirt, I wear a medium. I'm currently in the UK - if you prefer, I can try find someone in Perth to hold it for me until I'm next over.

**Comment by LegoStormtroopr** [comment]
Awesome work, thanks a bunch!

I'm in Canberra so I was going to have to mail them somewhere anyway. So I can just mail it to the UK anyway. Email me (sam[at]sqbl.org) with your details and I'll get it sorted this week.

**Pull request merged**
