### PR TITLE
Bugfix/827 flake8 on views lite

### PR DESCRIPTION
**Pull request by derrix060**
Some considerations:

- The major change was sort of import.
- Fix flake8 issues (except E501: max line length)
- Fix flake8 path on tox.ini
- Enable restrict flake8 on git diff. This will be good to standardize the errors that would be ignored across the code, or at least only in some specific parts using `# noqa`. This will also improve the code quality from new code, while I work to fix all the repository.

### CODE REVIEW

**Comment by derrix060** [comment]
Isn't travis working anymore?

**Comment by derrix060** [comment]
Maybe I need to merge the actual develop into my branch...

**Comment by harrywhite4** [comment]
The travis config has changed in develop so that could be it

**Comment by derrix060** [comment]
@harrywhite4 I tried to merge current develop into the branch and it didn't work. Can you please double check the configuration on Travis, or point me how to do it? I'm wondering if I had broken Travis with my changes :sob:

**Comment by derrix060** [comment]
NVM, I've found that I've broken the config :laughing:

**Pull request closed without merging**
