### PR TITLE
Update models.py to pass pep8 check

### PR DESCRIPTION
**Pull request by thsutton**
- [x] Add PEP8 check to travis build script (for `models.py` only at the moment)
- [x] Update `models.py` to pass the PEP8 check.

### CODE REVIEW

**Comment by thsutton** [comment]
I have done quite a bit of violence to the code style to make the pep8 check pass and, in general, tried to err on the side of consistency (e.g. breaking every kwarg to a model field constructor not just word wrapping them).

I also, in a handful of cases, used a temporary variable instead of splitting an expression across lines when resolving a long line warning.

If these changes are OK I'll go ahead and work through 5640 warnings in the rest of `aristotle_mdr/`.

**Comment by thsutton** [comment]
This is a start in addressing #149.

**Comment by LegoStormtroopr** [comment]
Looks great!

There are a lot of changes, are there any changes to fieldnames that have changed that might cause a migration?

**Comment by thsutton** [comment]
Nope: just whitespace, comments, and a few local variables for particularly long expressions which get passed in to `.filter()` (e.g. [this one](https://github.com/thsutton/aristotle-metadata-registry/blob/pep8/aristotle_mdr/models.py#L560)).

Given what the Django style guide says about line length I might just disable that check and revert some of the long-line changes.

**Comment by LegoStormtroopr** [comment]
Had a review and it looks great. I made a few big changes recently which caused a few conflicts but I've fixed that in my own 'pep8' branch which I've put a PR for.

**Comment by thsutton** [comment]
I started rebasing this but some of the merge conflicts are in substantive changes to the code, so I'll leave it here for the day. If you don't want to do the rebase then I'll cherry-pick the fixes to a single module (models.py) and get them merged one by one.

**Comment by LegoStormtroopr** [comment]
If the travis tests pass for this branch (without PEP8), I'm happy to incorporate what is here, and then start a fresh branch just for this.

**Comment by thsutton** [comment]
This now includes fixes to a bunch of little issues (syntax errors, tiny breaking changes in django-notifications 1.0, stupid stuff I did in earlier commits in this branch).

**Comment by thsutton** [comment]
I think this is ready to merge; I won't have time to get to the remaining modules until Friday at the earliest.

For the record: excluding `migrations/` (generated code) and `tests/` (just for now) there are 44 files only 14 of which have problems reported:

````
$ pep8 --exclude=migrations,tests --ignore=E501,E225,E123 aristotle_mdr/ | cut -d: -f1 | uniq -c
  83 aristotle_mdr/admin.py
  18 aristotle_mdr/autocomplete_light_registry.py
  13 aristotle_mdr/backends.py
  16 aristotle_mdr/comparators.py
  36 aristotle_mdr/downloader.py
  58 aristotle_mdr/perms.py
  23 aristotle_mdr/register.py
  55 aristotle_mdr/required_settings.py
  16 aristotle_mdr/search_indexes.py
  40 aristotle_mdr/forms/bulk_actions.py
   6 aristotle_mdr/urls/__init__.py
   8 aristotle_mdr/urls/aristotle.py
   5 aristotle_mdr/urls/base.py
  37 aristotle_mdr/views/bulk_actions.py
````

**Comment by LegoStormtroopr** [comment]
Amazing work!
Very happy to pull this in to make PEP testing a part of the test suite.
I'll email you to discuss your shirt soon!

**Comment by LegoStormtroopr** [comment]
FYI: I've PEP8'd aristotle_mdr/downloader.py in my current working branch.

To keep things clean, I'd suggest looking at admin.py, register.py, forms or urls as a starting point.
I'm doing some work in views, but can clean those up as I go through.

**Pull request merged**
